# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='\u62a5\u544a')),
                ('begin_time', models.DateField()),
                ('end_time', models.DateField()),
                ('report_type', models.CharField(choices=[('W', '\u5468\u62a5\u544a'), ('M', '\u6708\u62a5\u544a'), ('Y', '\u5e74\u62a5\u544a')], max_length=1)),
            ],
        ),
    ]
