# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ex_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='totle_new_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u65b0\u589e\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='report',
            name='totle_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u603b\u8ba2\u5355\u91cf'),
        ),
        migrations.AddField(
            model_name='report',
            name='totle_order_bathroom',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u536b\u6d74\u8ba2\u5355\u91cf'),
        ),
        migrations.AddField(
            model_name='report',
            name='totle_order_clotheshorse',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u667e\u8863\u67b6\u8ba2\u5355\u91cf'),
        ),
        migrations.AddField(
            model_name='report',
            name='totle_order_doorsandwindows',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u95e8\u7a97\u8ba2\u5355\u91cf'),
        ),
        migrations.AddField(
            model_name='report',
            name='totle_order_price',
            field=models.FloatField(blank=True, null=True, verbose_name='\u8ba2\u5355\u603b\u989d'),
        ),
        migrations.AddField(
            model_name='report',
            name='totle_order_tracery',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u7a97\u9970\u8ba2\u5355\u91cf'),
        ),
    ]
